### ISSUE TITLE
conda install mpi4py-fft

### ISSUE THREAD

**Issue by apatlpo** [spectralDNS/shenfun#20]
This may be a trivial question but: why is it that, when I install shenfun via conda, mpi4py-fft is not installed even though it is listed as a dependency in the [install doc](https://shenfun.readthedocs.io/en/latest/installation.html) ?

**Comment by mikaem** [comment]
I really don't know. It should be installed. This is when you try to install using conda install from the spectralDNS channel? What happens if you do pip install shenfun instead?

**Comment by apatlpo** [comment]
After installing numpy:
```
(shenfun_pip) br146-058:swpy aponte$ pip install shenfun
Collecting shenfun
  Using cached https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz
Collecting mpi4py-fft (from shenfun)
  Downloading https://files.pythonhosted.org/packages/7b/de/800bfa077a5b7cc43fc37fd6136113c11c3f07c31c1aa044f72e28710e76/mpi4py-fft-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-7idjfhed/mpi4py-fft/setup.py", line 89, in <module>
        fftw_libs = get_fftw_libs()
      File "/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-7idjfhed/mpi4py-fft/setup.py", line 44, in get_fftw_libs
        assert len(libs) > 0, "No FFTW libraries found in {} {}".format(library_dirs, sys.prefix)
    AssertionError: No FFTW libraries found in ['/Users/aponte/.miniconda3/envs/shenfun_pip/lib'] /Users/aponte/.miniconda3/envs/shenfun_pip

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-7idjfhed/mpi4py-fft/
(shenfun_pip) br146-058:swpy aponte$
```
Does this mean I have to install an fftw library beforehand?

**Comment by apatlpo** [comment]
With pip, I followed:
```
conda create -n shenfun_pip -c conda-forge python=3.6
conda activate shenfun_pip
conda install -c conda-forge mpi4py mpich fftw
pip install shenfun
```
leads:
```
(shenfun_pip) br146-058:swpy aponte$ pip install shenfun
Collecting shenfun
  Using cached https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-dcx1ik6p/shenfun/setup.py", line 8, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-dcx1ik6p/shenfun/
```
After installing numpy via conda, here is what happens:
```
(shenfun_pip) br146-058:swpy aponte$ pip install shenfun
Collecting shenfun
  Using cached https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz
Collecting mpi4py-fft (from shenfun)
Requirement already satisfied: mpi4py in /Users/aponte/.miniconda3/envs/shenfun_pip/lib/python3.6/site-packages (from shenfun) (3.0.0)
Requirement already satisfied: numpy in /Users/aponte/.miniconda3/envs/shenfun_pip/lib/python3.6/site-packages (from shenfun) (1.15.4)
Collecting scipy (from shenfun)
  Using cached https://files.pythonhosted.org/packages/a0/b6/70bf61c1badb5fea82d4c558e05e76c2dee5e77bb072fe465d7c7a87287d/scipy-1.1.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: shenfun
  Running setup.py bdist_wheel for shenfun ... error
  Complete output from command /Users/aponte/.miniconda3/envs/shenfun_pip/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-wheel-70gcqcua --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun
  copying shenfun/tensorproductspace.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
  copying shenfun/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
  copying shenfun/matrixbase.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
  copying shenfun/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
  copying shenfun/spectralbase.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/optimization
  copying shenfun/optimization/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/optimization
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  copying shenfun/legendre/lobatto.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  copying shenfun/legendre/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  copying shenfun/legendre/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  copying shenfun/legendre/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  copying shenfun/legendre/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
  copying shenfun/chebyshev/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
  copying shenfun/chebyshev/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
  copying shenfun/chebyshev/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
  copying shenfun/chebyshev/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
  copying shenfun/fourier/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
  copying shenfun/fourier/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
  copying shenfun/fourier/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  copying shenfun/forms/inner.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  copying shenfun/forms/arguments.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  copying shenfun/forms/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  copying shenfun/forms/operators.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  copying shenfun/forms/project.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
  copying shenfun/utilities/integrators.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
  copying shenfun/utilities/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
  copying shenfun/utilities/lagrangian_particles.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
  creating build/lib.macosx-10.9-x86_64-3.6/shenfun/io
  copying shenfun/io/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
  copying shenfun/io/nc_file.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
  copying shenfun/io/h5py_file.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
  running build_ext
  building 'shenfun.optimization.Matvec' extension
  error: unknown file type '.pyx' (from '/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/shenfun/optimization/Matvec.pyx')

  ----------------------------------------
  Failed building wheel for shenfun
  Running setup.py clean for shenfun
Failed to build shenfun
Installing collected packages: mpi4py-fft, scipy, shenfun
  Running setup.py install for shenfun ... error
    Complete output from command /Users/aponte/.miniconda3/envs/shenfun_pip/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-record-w_kp7_9m/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun
    copying shenfun/tensorproductspace.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
    copying shenfun/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
    copying shenfun/matrixbase.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
    copying shenfun/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
    copying shenfun/spectralbase.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/optimization
    copying shenfun/optimization/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/optimization
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    copying shenfun/legendre/lobatto.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    copying shenfun/legendre/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    copying shenfun/legendre/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    copying shenfun/legendre/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    copying shenfun/legendre/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/legendre
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
    copying shenfun/chebyshev/la.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
    copying shenfun/chebyshev/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
    copying shenfun/chebyshev/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
    copying shenfun/chebyshev/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/chebyshev
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
    copying shenfun/fourier/matrices.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
    copying shenfun/fourier/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
    copying shenfun/fourier/bases.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/fourier
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    copying shenfun/forms/inner.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    copying shenfun/forms/arguments.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    copying shenfun/forms/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    copying shenfun/forms/operators.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    copying shenfun/forms/project.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/forms
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
    copying shenfun/utilities/integrators.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
    copying shenfun/utilities/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
    copying shenfun/utilities/lagrangian_particles.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/utilities
    creating build/lib.macosx-10.9-x86_64-3.6/shenfun/io
    copying shenfun/io/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
    copying shenfun/io/nc_file.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
    copying shenfun/io/h5py_file.py -> build/lib.macosx-10.9-x86_64-3.6/shenfun/io
    running build_ext
    building 'shenfun.optimization.Matvec' extension
    error: unknown file type '.pyx' (from '/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/shenfun/optimization/Matvec.pyx')

    ----------------------------------------
Command "/Users/aponte/.miniconda3/envs/shenfun_pip/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-record-w_kp7_9m/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/h9/bddhh5015njbwrc_3shcvsnh0000gp/T/pip-install-k8ko7766/shenfun/
(shenfun_pip) br146-058:swpy aponte$
```

**Comment by mikaem** [comment]
You actually need to conda install pip as well to use pip inside a conda environment. I think that's the problem and I see that it's not stated explicitly in the installation instructions. You can test which pip by typing in a terminal
    
    which pip

If you look at the setup.py you'll see that numpy is listed both as an ``install_requirement`` and a ``setup_requirement``, so you should normally not need to worry about this. Unknown filetype pyx is a problem with Cython not being installed. But all this should go away I think if pip is installed in the environment, because cython is also a setup and install requirement. Mixing conda and pip is not always highly recommended:-)

**Comment by apatlpo** [comment]
pip was actually installed when I created the conda environment and a `which pip` points to this same environment.

**Comment by mikaem** [comment]
I'm pretty sure your recipe
    
    conda create -n shenfun_pip -c conda-forge python=3.6
    conda activate shenfun_pip
    conda install -c conda-forge mpi4py mpich fftw
    pip install shenfun

creates an environment shenfun_pip, where pip is not installed. And then you get errors when you run pip install shenfun. Otherwise I see no possible explanation for the strange numpy and cython errors.

**Comment by apatlpo** [comment]
ok, I'll double check right away

**Comment by apatlpo** [comment]
Here is the full log of the install first step:
```
br146-058:~ aponte$ conda create -n shenfun_pip -c conda-forge python=3.6
Solving environment: done

## Package Plan ##

  environment location: /Users/aponte/.miniconda3/envs/shenfun_pip

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

    ca-certificates: 2018.11.29-ha4d7672_0 conda-forge
    certifi:         2018.11.29-py36_1000  conda-forge
    libffi:          3.2.1-hfc679d8_5      conda-forge
    ncurses:         6.1-hfc679d8_2        conda-forge
    openssl:         1.0.2p-h470a237_1     conda-forge
    pip:             18.1-py36_1000        conda-forge
    python:          3.6.7-h5001a0f_1      conda-forge
    readline:        7.0-haf1bffa_1        conda-forge
    setuptools:      40.6.3-py36_0         conda-forge
    sqlite:          3.26.0-hb1c47c0_0     conda-forge
    tk:              8.6.9-ha92aebf_0      conda-forge
    wheel:           0.32.3-py36_0         conda-forge
    xz:              5.2.4-h470a237_1      conda-forge
    zlib:            1.2.11-h470a237_3     conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate shenfun_pip
#
# To deactivate an active environment, use
#
#     $ conda deactivate

br146-058:~ aponte$ conda activate shenfun_pip
(shenfun_pip) br146-058:~ aponte$ which pip
/Users/aponte/.miniconda3/envs/shenfun_pip/bin/pip
```

**Comment by mikaem** [comment]
Hm, ok, that is very strange.

**Comment by mikaem** [comment]
How is it possible that pip complains over missing numpy?

**Comment by mikaem** [comment]
I was under the impression that pip would install setup_requirements for you?

**Comment by apatlpo** [comment]
About the numpy failure with pip, I am under the impression that pip does not have the chance to install numpy because of the import statement in the setup file:
```
(shenfun_pip) datahome/aponte% pip install shenfun -v
Created temporary directory: /tmp/pip-ephem-wheel-cache-8hz5lj3d
Created temporary directory: /tmp/pip-req-tracker-bruij0ma
Created requirements tracker '/tmp/pip-req-tracker-bruij0ma'
Created temporary directory: /tmp/pip-install-mvt9fpgj
Collecting shenfun
  1 location(s) to search for versions of shenfun:
  * https://pypi.org/simple/shenfun/
  Getting page https://pypi.org/simple/shenfun/
  Looking up "https://pypi.org/simple/shenfun/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/shenfun/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/shenfun/
    Found link https://files.pythonhosted.org/packages/4e/a8/29c194b55d9ba59ae5edf6100d0aed92d4c22e8c3d839d959f5c5b7b9a0a/shenfun-1.1.tar.gz#sha256=a7cb126fa9ffec70eff948251545a5ecf6bc524aca5ac27f3023bc6b65bcb8c0 (from https://pypi.org/simple/shenfun/), version: 1.1
    Found link https://files.pythonhosted.org/packages/6c/53/dbaf072c1afe7b8d3e7e334a029342ce596ded2cd4fe2ad4c238b958157c/shenfun-1.1.1.tar.gz#sha256=54ece01fd3eb8418a820f59c3b172b8bcbc309107c3d437c9172d489a291d48c (from https://pypi.org/simple/shenfun/), version: 1.1.1
    Found link https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz#sha256=a0cd7b5c675879f4f46704d2136a56ea7dabe7bc9edd4ff8f36948bc4c314378 (from https://pypi.org/simple/shenfun/), version: 1.2.0
  Using version 1.2.0 (newest of versions: 1.1, 1.1.1, 1.2.0)
  Created temporary directory: /tmp/pip-unpack-a37cg289
  Looking up "https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz" in the cache
  Current age based on date: 526
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 526
  Using cached https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz#sha256=a0cd7b5c675879f4f46704d2136a56ea7dabe7bc9edd4ff8f36948bc4c314378 (from https://pypi.org/simple/shenfun/)
  Added shenfun from https://files.pythonhosted.org/packages/85/b2/852c7add38e6bcfd2ea4379888731fe58a2280ffc176277006db1f340995/shenfun-1.2.0.tar.gz#sha256=a0cd7b5c675879f4f46704d2136a56ea7dabe7bc9edd4ff8f36948bc4c314378 to build tracker '/tmp/pip-req-tracker-bruij0ma'
  Running setup.py (path:/tmp/pip-install-mvt9fpgj/shenfun/setup.py) egg_info for package shenfun
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mvt9fpgj/shenfun/setup.py", line 8, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'
Cleaning up...
...
```

**Comment by mikaem** [comment]
No, you can say the same thing about setuptools. This is why both numpy and setuptools are in the setup_requires list.

**Comment by apatlpo** [comment]
ok, clearly I don't much about the packaging process and I am afraid I won't be of much help.
Sorry about that.

**Comment by mikaem** [comment]
But if you install numpy and cython by hand, then everything is ok?

**Comment by apatlpo** [comment]
The following:
```
conda create -n shenfun_pip -c conda-forge python=3.6
conda activate shenfun_pip
conda install -c conda-forge mpi4py mpich fftw numpy cython
pip install shenfun
```
does install mpi4py-fft, yes

I am in the process of checking the libraries are functional now

**Comment by apatlpo** [comment]
Note that sympy was not installed though

**Comment by mikaem** [comment]
That's ok. Sympy is not a required dependency, even though it should probably be so.

**Comment by apatlpo** [comment]
ok, install seems to be functional:

- spectral_dns_solver.py from [mpi4py-fft demo](https://bitbucket.org/mpi4py/mpi4py-fft/src/master/examples/spectral_dns_solver.py) goes through fine

- dirichlet_poisson3D.py from [shenfun doc](https://shenfun.readthedocs.io/en/latest/poisson3d.html) (note: example call to this function in the doc needs to be updated with dimension length)
```
(shenfun_pip) r1i7n20 aponte/swpy% mpirun -n 4 python dirichlet_poisson3D.py 64 legendre
Error=4.7449508108832853e-13
Traceback (most recent call last):
  File "dirichlet_poisson3D.py", line 76, in <module>
    print("Error=%2.16e" %(np.sqrt(error)))
AttributeError: 'NoneType' object has no attribute 'sqrt'
```
The error is weird but the code seems to run through

**Comment by apatlpo** [comment]
Ok, the error is fixed if the following line is added before the print statement:
```
if comm.rank==0:
```

**Comment by mikaem** [comment]
Is np NoneType? 
Anyway, thanks a lot for all the feedback:-) I'll change the installation to use the version of mpi4py-fft that is available now from conda-forge. That should take care of the original problem of this issue. Regarding all the other problems, I'm still not much wiser, but it couldn't hurt to add numpy and cython to the installation docs as well:-)

**Comment by mikaem** [comment]
The comm.rank == 0 is actually already there in the official demo:-) Just the documentation that needs to be updated I guess.
